import { Injectable } from "@angular/core";

import { FlightRecorderLogData } from "./flight-recorder-log-data";

/**
 * Interface matching the WASM FlightRecorderClient.
 * This will be generated by sdk-internal once the SDK is built with Flight Recorder support.
 */
interface FlightRecorderClient {
  drain(): FlightRecorderLogData[];
  count(): number;
}

/**
 * Service for exporting Flight Recorder logs.
 * Wraps the WASM FlightRecorderClient for Angular DI.
 */
@Injectable({ providedIn: "root" })
export class FlightRecorderService {
  private client: FlightRecorderClient | null = null;

  constructor() {
    // FlightRecorderClient accesses the global buffer initialized by init_sdk()
    // Dynamically import to handle cases where SDK doesn't have FlightRecorderClient yet
    void this.initializeClient();
  }

  private async initializeClient(): Promise<void> {
    try {
      const sdkInternal = await import("@bitwarden/sdk-internal");
      if ("FlightRecorderClient" in sdkInternal) {
        const FlightRecorderClientClass = (sdkInternal as any).FlightRecorderClient;
        this.client = new FlightRecorderClientClass();
      }
    } catch {
      // SDK doesn't have FlightRecorderClient yet - this is expected during development
      // This is intentional - we silently fail if SDK doesn't have FlightRecorderClient
    }
  }

  /**
   * Drain all events from the SDK buffer and return them.
   * WARNING: This empties the buffer - events are only returned once.
   */
  drain(): FlightRecorderLogData[] {
    if (!this.client) {
      return [];
    }
    return this.client.drain();
  }

  /**
   * Get current event count without draining.
   */
  count(): number {
    if (!this.client) {
      return 0;
    }
    return this.client.count();
  }

  /**
   * Export logs as formatted JSON string for download.
   */
  exportAsJson(): string {
    const events = this.drain();
    return JSON.stringify(events, null, 2);
  }

  /**
   * Export logs as plain text for download.
   */
  exportAsPlainText(): string {
    const events = this.drain();
    return events
      .map(
        (e) =>
          `[${new Date(e.timestamp).toISOString()}] ${e.level.toUpperCase()} ${e.target}: ${e.message}`,
      )
      .join("\n");
  }

  /**
   * Check if the Flight Recorder client is available.
   */
  isAvailable(): boolean {
    return this.client !== null;
  }
}
