/**
 * Type declarations for @bitwarden/sdk-internal Flight Recorder exports.
 *
 * These types will be generated by the SDK once bitwarden-flight-recorder is built.
 * This file provides type stubs to allow clients code to compile before the SDK is updated.
 *
 * TODO: Remove this file once @bitwarden/sdk-internal exports FlightRecorderClient.
 */

import { FlightRecorderLogData } from "./flight-recorder-log-data";

declare module "@bitwarden/sdk-internal" {
  export class FlightRecorderClient {
    constructor();
    drain(): FlightRecorderLogData[];
    count(): number;
  }
}
